name: Prod
color: "#B83D7F"
variables:
  - name: baseUrl
    value: https://api.aptitude-registry.dev
  - secret: true
    name: readToken
  - secret: true
    name: publishToken
  - secret: true
    name: adminToken
