"""Semantic discovery defaults shared by settings, adapters, docs, and tests."""

from __future__ import annotations

from typing import Literal

SemanticEmbeddingProvider = Literal["openai"]

DEFAULT_SEMANTIC_DISCOVERY_MODE = "off"
DEFAULT_SEMANTIC_EMBEDDING_PROVIDER: SemanticEmbeddingProvider = "openai"
DEFAULT_SEMANTIC_EMBEDDING_MODEL = "text-embedding-3-small"
DEFAULT_SEMANTIC_EMBEDDING_SOURCE_VERSION = "description-tags-v1"
DEFAULT_SEMANTIC_EMBEDDING_INDEX_KEY = (
    f"{DEFAULT_SEMANTIC_EMBEDDING_PROVIDER}:"
    f"{DEFAULT_SEMANTIC_EMBEDDING_MODEL}:"
    f"{DEFAULT_SEMANTIC_EMBEDDING_SOURCE_VERSION}"
)
DEFAULT_SEMANTIC_EMBEDDING_DIMENSIONS = 1536
DEFAULT_SEMANTIC_CANDIDATE_LIMIT = 20
DEFAULT_SEMANTIC_QUERY_TIMEOUT_MS = 150
DEFAULT_SEMANTIC_HNSW_EF_SEARCH = 100
DEFAULT_SEMANTIC_INDEX_BATCH_SIZE = 25
DEFAULT_SEMANTIC_INDEX_MAX_BATCHES = 1
DEFAULT_SEMANTIC_RECLAIM_AFTER_SECONDS = 3600
